### ISSUE TITLE
Wrong variable in reset_count()

### ISSUE THREAD

**Issue by palmerr23** [tobiglaser/RP2040-Encoder#2]
Line should read ("count" used instead of "cnt"):
`void reset_count(int new_value = 0) { cnt = new_value; }`

**Comment by tobiglaser** [comment]
Thank you! Crazy how I never called this function.
Should be fixed in [c5f96d8](https://github.com/tobiglaser/RP2040-Encoder/commit/c5f96d858ca22125a64f759b016c2e761e93986d).
